// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqhouenplcddjtqapurn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxaG91ZW5wbGNkZGp0cWFwdXJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzQzOTYsImV4cCI6MjA2NzY1MDM5Nn0.kxH5aWrtCw6UMYssm8zgTwQrt5CH4-kJk-H3bcajA3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});